name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - name: Lint and fix MDX
        env:
          MDX_LINT_CONFIG: .eslintrc.json  
        run: yarn run lint-mdx --config "$MDX_LINT_CONFIG"